spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/workload
server:
  port: 8081
  error:
    include-message: always