spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5432/workload
server:
  port: 8081
  error:
    include-message: always

jwt:
  key: "thisIsJwtSignatureKeyblahbluhblihbleh1283y9hdsakjhjk3hjkshaf72gulhgjhdsjlhh4khslkdfhl2asdshf3jguihgbdsjgh2d"